name: Android Debug APK

on:
  workflow_dispatch:      # allows you to run manually
  push:
    branches: [ main ]    # or automatically on main branch pushes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Build debug APK
        run: ./gradlew --no-daemon :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
